# Action fragment for the IMS-access (RBAC) add-on. $included by
# app.config.yaml under application.runtimeManifest.packages.ImsAccess.
license: Apache-2.0
actions:
  ims-user-profile:
    function: ims-user-profile/index.js
    web: 'yes'
    runtime: 'nodejs:20'
    limits:
      concurrency: 200
      memory: 256
    inputs:
      LOG_LEVEL: debug
      OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
      OAUTH_CLIENT_SECRET: $OAUTH_CLIENT_SECRET
      OAUTH_ORG_ID: $OAUTH_ORG_ID
      OAUTH_SCOPES: $OAUTH_SCOPES
      AIO_DB_REGION: $AIO_DB_REGION
      SUPER_ADMIN_EMAILS: $SUPER_ADMIN_EMAILS
    annotations:
      require-adobe-auth: false
      include-ims-credentials: true
      final: true
  access-list:
    function: access-list/index.js
    web: 'yes'
    runtime: 'nodejs:20'
    limits:
      concurrency: 200
      memory: 256
    inputs:
      LOG_LEVEL: debug
      OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
      OAUTH_CLIENT_SECRET: $OAUTH_CLIENT_SECRET
      OAUTH_ORG_ID: $OAUTH_ORG_ID
      OAUTH_SCOPES: $OAUTH_SCOPES
      AIO_DB_REGION: $AIO_DB_REGION
      SUPER_ADMIN_EMAILS: $SUPER_ADMIN_EMAILS
    annotations:
      require-adobe-auth: false
      include-ims-credentials: true
      final: true
  access-save:
    function: access-save/index.js
    web: 'yes'
    runtime: 'nodejs:20'
    limits:
      concurrency: 200
      memory: 256
    inputs:
      LOG_LEVEL: debug
      OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
      OAUTH_CLIENT_SECRET: $OAUTH_CLIENT_SECRET
      OAUTH_ORG_ID: $OAUTH_ORG_ID
      OAUTH_SCOPES: $OAUTH_SCOPES
      AIO_DB_REGION: $AIO_DB_REGION
      SUPER_ADMIN_EMAILS: $SUPER_ADMIN_EMAILS
    annotations:
      require-adobe-auth: false
      include-ims-credentials: true
      final: true
  access-delete:
    function: access-delete/index.js
    web: 'yes'
    runtime: 'nodejs:20'
    limits:
      concurrency: 200
      memory: 256
    inputs:
      LOG_LEVEL: debug
      OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
      OAUTH_CLIENT_SECRET: $OAUTH_CLIENT_SECRET
      OAUTH_ORG_ID: $OAUTH_ORG_ID
      OAUTH_SCOPES: $OAUTH_SCOPES
      AIO_DB_REGION: $AIO_DB_REGION
      SUPER_ADMIN_EMAILS: $SUPER_ADMIN_EMAILS
    annotations:
      require-adobe-auth: false
      include-ims-credentials: true
      final: true
